### ISSUE TITLE
xsd validation reports an error for maxOccurs

### ISSUE THREAD

**Issue by Msch0150** [ewg118/NUDS#3]
I made some tests to map the nuds.xsd with Excel.
During the map (Developer > Source > XML Maps > Add ... (remove the line with the import xml.xsd to avoid a duplication error))  I do get the error:
description: /schema/element[18][@name = 'rightsStmt']/complexType81]/all[1]/element[2]
'maxOccurs' of all the particles in an <all> group must be either 0 or 1.

I vailidated the nuds.xsd with an other tool: 

http://www.utilities-online.info/xsdvalidation/

And it reports the same error for Line 343 (2 times) and line 1320 (1 time).

Info: if I exchange "unbounded" to "0" or "1" for these 3 lines, then the validation is OK.

**Comment by ewg118** [comment]
I have resolved this by making rightsStmt an xs:sequence and allowing only one description for a findspot
